name: music_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  external_path: ^1.0.3
  file_manager: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

fonts:
  - family: Noto
    fonts:
      - asset: assets/fonts/Noto/NotoSans-Light.ttf
        weight: 300
      - asset: assets/fonts/Noto/NotoSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/Noto/NotoSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/Noto/NotoSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Noto/NotoSans-Bold.ttf
        weight: 700
